/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_FisNano_FiscalMemory */

#ifndef _Included_com_FisNano_FiscalMemory
#define _Included_com_FisNano_FiscalMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    OpenDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_OpenDevice
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    CloseDevie
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_FisNano_FiscalMemory_CloseDevie
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    GetFiscalCode
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_FisNano_FiscalMemory_GetFiscalCode
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    SetFiscalCode
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_SetFiscalCode
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    GetFiscalNum
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_FisNano_FiscalMemory_GetFiscalNumber(JNIEnv *env, jobject self);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    SetFiscalNum
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_SetFiscalNumber
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    SendDataOfEntry
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_SendDataOfEntry
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    GetNumberOfEntries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_GetNumberOfEntries
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    SetEntryIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_SetEntryIndex
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    GetEntryData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_FisNano_FiscalMemory_GetEntryData
        (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_SetEntryData
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    GetFreeEntries
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_GetFreeEntries
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    ClearCompleteCard
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_ClearCompleteCard
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    SoftwareReset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_SoftwareReset
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    SetFiscalRevolingAmount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_SetFiscalRevolingAmount
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    GetFiscalRevolingAmount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_GetFiscalRevolingAmount
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    SetMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL
Java_com_FisNano_FiscalMemory_SetMode(JNIEnv *env, jobject thiz, jboolean enable_user_mode);


/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    GetFirmwareInfo
 * Signature: ()[B
 */
JNIEXPORT jstring JNICALL Java_com_FisNano_FiscalMemory_GetFirmwareInfo
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    GetDailySalesTotalSum
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_FisNano_FiscalMemory_GetDailySalesTotalSum
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    GetDailySalesTaxSum
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_FisNano_FiscalMemory_GetDailySalesTaxSum
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    SetDailySalesTotalSumRangeByIndex
 * Signature: (IJ)Z
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_SetDailySalesTotalSumRangeByIndex
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    SetDailySalesTotalSumRangeByDateTime
 * Signature: (Ljava/util/Date;J)Z
 */
JNIEXPORT jint JNICALL Java_com_FisNano_FiscalMemory_SetDailySalesTotalSumRangeByDateTime
        (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    DailySalesTotalSumRange
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_FisNano_FiscalMemory_GetDailySalesTotalSumRange
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    DailySalesTaxSumRange
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_FisNano_FiscalMemory_GetDailySalesTaxSumRange
        (JNIEnv *, jobject);

/*
 * Class:     com_FisNano_FiscalMemory
 * Method:    GetFiscalNumberStatus
 * Signature: ()J
 */
//JNIEXPORT jboolean JNICALL
//Java_com_FisNano_FiscalMemory_GetFiscalNumberStatus(JNIEnv *env, jobject thiz);
//
//JNIEXPORT jboolean JNICALL
//Java_com_FisNano_FiscalMemory_GetFiscalCodeStatus(JNIEnv *env, jobject thiz);
//
//JNIEXPORT jboolean JNICALL
//Java_com_FisNano_FiscalMemory_GetFiscalRevolvingAmountStatus(JNIEnv *env, jobject thiz);
JNIEXPORT jboolean JNICALL
Java_com_FisNano_FiscalMemory_GetFullStatus(JNIEnv *env, jobject thiz);
JNIEXPORT void JNICALL
Java_com_FisNano_FiscalMemory_SetFullStatus(JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
